Feature/login 로그인 기능 구현 완료
wecode-bootcamp-korea/40-1st-Dyong-backend pull request #3
Opened 2022-12-09 04:32 UTC by dozksms

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- username, password를 이용한 로그인 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 해당 API로 ‎요청이 들어오면 유효성 검사후 상황에 맞는 response 전송

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![스크린샷 2022-12-09 13 28 12](https://user-images.githubusercontent.com/110329696/206624215-c6fc0c67-9d0f-4845-b394-45076cc6aa64.png)
3. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
- 유효성검사가 통과된 경우
<img width="1072" alt="스크린샷 2022-12-09 13 29 44" src="https://user-images.githubusercontent.com/110329696/206624353-3ded99f6-46cd-4e87-a124-6813c93343b4.png">
- 통과 안됬을 경우
<img width="1084" alt="스크린샷 2022-12-09 13 30 11" src="https://user-images.githubusercontent.com/110329696/206624464-f48feaec-9512-4ed4-a118-ca25745e1ae0.png">

5. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-09 09:59 UTC, kyeongraekim requested changes

2022-12-09 09:59 UTC, kyeongraekim commented on models/userDao.js
> +    SELECT *
실제 어떤 컬럼의 데이터를 끌고 오는지 코드상에서 명확해야 제 3자 개발자의 가독성이 확보될 것 같네요! asterisk 문의 사용은 꼭 필요한 경우가아니면 사용을 지양해주세요!~

2022-12-09 12:20 UTC, dozksms commented on models/userDao.js
> +    SELECT *
넵!!

2022-12-12 02:01 UTC, kyeongraekim approved these changes
LGTM!~

2022-12-12 02:01 UTC, merged