[40기 - 이정우] 전체상품 GET요청 API 구현완료
wecode-bootcamp-korea/40-1st-Dyong-backend pull request #5
Opened 2022-12-09 15:43 UTC by dozksms

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 전체 상품페이지 GET요청 기능 구현
‎<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 해당 URL로 GET요청이 들어올 시 전체상품 데이터를 response 해주는 API 구현 완료
<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="265" alt="스크린샷 2022-12-10 00 41 01" src="https://user-images.githubusercontent.com/110329696/206738824-90dead6e-10ae-48b0-9e13-2497a0081e2f.png">
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="1074" alt="스크린샷 2022-12-10 00 38 12" src="https://user-images.githubusercontent.com/110329696/206738576-a40f5a21-f624-4bba-be10-0f78df852dd9.png">
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)
 - datasource를 app.js에서 만든 후 DAO파일에 import 해서 사용할때 query 메서드는 왜 사용이 안되는 건가요??
 class 개념이라며는 안에 있는 메서드 도 사용 가능‎해지는거 아닌가요,,? ㅜㅜ

2022-12-10 18:29 UTC, dozksms commented
pagination까지 구현 완료까지 하겠습니다!

2022-12-12 02:18 UTC, kyeongraekim requested changes

2022-12-12 02:18 UTC, kyeongraekim commented on models/productsDao.js
> +    ON
가독성 향상을 위해서 SELECT 와 같은 구문과 나머지 컬럼의 인덴테이션 구분을 지어주면 좋을 것 같네요! 아래 예시를 참고해주세요!
```javascript
SELECT
    p.name
FROM
    products

2022-12-12 02:18 UTC, kyeongraekim commented on controllers/productsControllers.js
> +} = require('../models/productsDao.js');
Controller에서 Dao를 바로 호출하고 있네요! 관심사 분리가 Service단을 중심으로 이루어지고 있지 않습니다. 해당 내용 수정해주세요!~

2022-12-12 02:18 UTC, kyeongraekim commented on models/productsDao.js
> +    if (type.length === 1) {
- 해당 type.length 로의 분기는 어떤 내용을 의미하는 것일까요?
- 이 부분을 기준으로 아래 SQL Query문의 where로 분기되어서 데이터들이 인자로 전달되는 것 같아 보이는데.. 해당 내용을 Service에서 처리해서 전달할 수 있게 변경해보세요!

2022-12-12 02:18 UTC, kyeongraekim commented on models/productsDao.js
> +  }
이 부분은 Dao가 아닌 서비스에 있어야할 내용처럼 보이네요!

해당 내용은 단순 문자열의 비교만으로 이루어질 수 있음으로, if 문보다 더 효과적이고 경제적인 Switch-Case문을 도입하여 리팩토링 해보실 수 있을 겁니다.

아래의 참고 예시를 살펴봐주세요! 정확히 동일하게 따라하지마시고 아래 내용을 기반으로 응용해서 자신의 코드에 맞게 적용해주세요!

```javascript
const categoryService = async(categoryId, offset, limit, minPrice, maxPrice, sortBy) => {

    const ordering = async(sortBy) => {

        switch(sortBy){
            case 'priceASC':
                return `ORDER BY o.price ASC, o.id ASC`
            case 'priceDESC':
                return `ORDER BY o.price DESC, o.id ASC`
            case 'nameASC':
                return `ORDER BY productName ASC, o.id ASC`
            case 'newest':
                return `ORDER BY p.created_at DESC, o.id ASC`
            default:
                return `ORDER BY o.id`
        }
    };

    const priceRange = async(minPrice, maxPrice) => {

        if (!minPrice && !maxPrice) return ` AND o.price>=0`

        if (minPrice===0)           return ` AND (o.price>=0 AND o.price<${maxPrice})`

        return  ` AND (o.price>=${minPrice} AND o.price<${maxPrice})`;

    };

    const orderingQuery = await ordering(sortBy);
    const priceRangeQuery = await priceRange(minPrice, maxPrice);

    return await categoryDao.getProductsByCat(categoryId, offset, limit, orderingQuery, priceRangeQuery);

2022-12-12 02:55 UTC, dozksms commented on models/productsDao.js
> +  }
switch문 구글링 후 응용해서 적용 해보겠습니다!! 감사합니다!!

2022-12-13 02:12 UTC, kyeongraekim requested changes

2022-12-13 02:12 UTC, kyeongraekim commented on services/productsService.js
> +  getCategoryBySortQuery,
Conflict 해결해주시다가 중복 코드들이 들어간 것 처럼 보이네요! 수정해주세요!~

2022-12-13 02:12 UTC, kyeongraekim commented on controllers/productsControllers.js
> +      const data = await sortOnly(sort, page, category);
해당 내용은 에러핸들링 미들웨어를 사용해서 처리하는 방법으로 리팩토링에 도전해보세요! 비동기 에러를 컨트롤러 단에서 처리하려면 별도의 에러함수가 필요할 수 있는데 아래의 링크를 한 번 참고해주세요!~
[링크 바로가기](https://thecodebarbarian.com/80-20-guide-to-express-error-handling)

2022-12-13 05:05 UTC, dozksms commented on controllers/productsControllers.js
> +      const data = await sortOnly(sort, page, category);
넵 참고해서 수정 하겠습니다!

2022-12-13 13:51 UTC, dozksms commented on controllers/productsControllers.js
> +      const data = await sortOnly(sort, page, category);
보내주신 링크 참고해서 error handling middleware 를 사용해서 controller에서는 리팩토링을 완료했습니다!
근데 혹시 middleware를 통해서 error를 catch 해주기 때문에 Dao파일과 service파일에 있는 try catch구문도 빠져도 되는건가요??

2022-12-14 09:08 UTC, kyeongraekim approved these changes
LGTM!~ 추후 리팩토링 과제 로그 기록물 형태로 메모하시면서 작업에 임하시면 더 좋을 것 같아보이네요!

2022-12-14 09:08 UTC, merged

2022-12-14 09:30 UTC, dozksms commented
> LGTM!~ 추후 리팩토링 과제 로그 기록물 형태로 메모하시면서 작업에 임하시면 더 좋을 것 같아보이네요!
넵!!